# Project: Airline Reservation
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = Flight.o DomesticFlight.o InternationalFlight.o CharterFlight.o Passenger.o EconomyPassenger.o BusinessPassenger.o FirstClassPassenger.o Ticket.o Airline.o main.o
LINKOBJ  = Flight.o DomesticFlight.o InternationalFlight.o CharterFlight.o Passenger.o EconomyPassenger.o BusinessPassenger.o FirstClassPassenger.o Ticket.o Airline.o main.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib"
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = "Airline Reservation.exe"
CXXFLAGS = $(CXXINCS) -std=c++11
CFLAGS   = $(INCS) -std=c++11
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

Flight.o: Flight.cpp
	$(CPP) -c Flight.cpp -o Flight.o $(CXXFLAGS)

DomesticFlight.o: DomesticFlight.cpp
	$(CPP) -c DomesticFlight.cpp -o DomesticFlight.o $(CXXFLAGS)

InternationalFlight.o: InternationalFlight.cpp
	$(CPP) -c InternationalFlight.cpp -o InternationalFlight.o $(CXXFLAGS)

CharterFlight.o: CharterFlight.cpp
	$(CPP) -c CharterFlight.cpp -o CharterFlight.o $(CXXFLAGS)

Passenger.o: Passenger.cpp
	$(CPP) -c Passenger.cpp -o Passenger.o $(CXXFLAGS)

EconomyPassenger.o: EconomyPassenger.cpp
	$(CPP) -c EconomyPassenger.cpp -o EconomyPassenger.o $(CXXFLAGS)

BusinessPassenger.o: BusinessPassenger.cpp
	$(CPP) -c BusinessPassenger.cpp -o BusinessPassenger.o $(CXXFLAGS)

FirstClassPassenger.o: FirstClassPassenger.cpp
	$(CPP) -c FirstClassPassenger.cpp -o FirstClassPassenger.o $(CXXFLAGS)

Ticket.o: Ticket.cpp
	$(CPP) -c Ticket.cpp -o Ticket.o $(CXXFLAGS)

Airline.o: Airline.cpp
	$(CPP) -c Airline.cpp -o Airline.o $(CXXFLAGS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)
